services:
  - type: web
    name: fb-sentiment-api
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: MODEL_PATH
        value: /app/models/best_marathi_sentiment_model.pth
      - key: FB_EMAIL
        sync: false
      - key: FB_PASSWORD
        sync: false
    healthCheckPath: /test-sentiment
    buildCommand: docker build -t fb-sentiment-api .
